### PR TITLE
fix: duplicated objects when charts are nested

### LINKED ISSUE #31: Duplicated synthed resources when nesting Charts
### Description of the bug:
When nesting charts within a parent chart, applying the parent chart to an app and then synthesizing the app, I'm seeing duplicated synthed resources - one file for each separate chart nested in the parent chart, and then one file for the parent chart which _also_ includes the resources from the nested charts. 

This is problematic when applying to Kubernetes using `kubectl apply -f dist/` as the files contain duplicate identically named resources. Not sure if this is expected or not but submitting as a bug report just in case 🙂 

### Reproduction Steps:

`app/test.ts`:
```typescript
import { App, Chart } from 'cdk8s'
import { Construct } from 'constructs'
import { Namespace } from '../imports/k8s';


export class ChildChart1 extends Chart {
    constructor(scope: Construct, name: string) {
      super(scope, name)
      const ns1 = new Namespace(this, 'namespace1')
    }
}

export class ChildChart2 extends Chart {
    constructor(scope: Construct, name: string) {
      super(scope, name)
      const ns2 = new Namespace(this, 'namespace2')
    }
}

export class ParentChart extends Chart {
    constructor(scope: Construct, name: string) {
        super(scope, name)
        const childChart1 = new ChildChart1(this, 'child1')
        const childChart2 = new ChildChart2(this, 'child2')
        const ns3 = new Namespace(this, 'namespace3')
    }
}
const app = new App()
const parent = new ParentChart(app, 'parent')
app.synth()
```

`shell`:
```shell
➜  cdk8s git:(feat/nested-children) ✗ cdk8s synth -a "npx ts-node -r tsconfig-paths/register app/test.ts"
dist/parent-child1-cad88a69.k8s.yaml
dist/parent-child2-1e516eb8.k8s.yaml
dist/parent.k8s.yaml

➜  cdk8s git:(feat/nested-children) ✗ cat dist/parent-child1-cad88a69.k8s.yaml
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "parent-child1-namespace1-e27612e5"

➜  cdk8s git:(feat/nested-children) ✗ cat dist/parent-child2-1e516eb8.k8s.yaml
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "parent-child2-namespace2-32aecabe"

➜  cdk8s git:(feat/nested-children) ✗ cat dist/parent.k8s.yaml
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "parent-child1-namespace1-e27612e5"
---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "parent-child2-namespace2-32aecabe"
---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "parent-namespace3-7362c69c"
```

### Environment:

```
cdk8s-test@0.0.1 
├── @types/jest@26.0.15
├── @types/node@14.14.6
├── cdk8s@0.33.0
├── cdk8s-cli@0.33.0
├── cdk8s-plus@0.33.0
├── constructs@3.2.11
├── dotenv@8.2.0
├── jest@26.6.3
├── npm-run-all@4.1.5
├── source-map@0.7.3
├── source-map-support@0.5.19
├── ts-jest@26.4.3
├── ts-node@9.0.0
├── tsconfig-paths@3.9.0
└── typescript@4.0.5
```

### Other:
I'm not bothered what the correct output is here. It seems to me that output should either be in individual files (one per nested child, with the parent resources in their own file) or all resources should be put into the one parent file. I don't think it matters, as long as the directory itself doesn't contain duplicate resources.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #31

I think the expected behavior from users is that in most circumstances, you should be able to directly apply resources generated by `cdk8s synth` to your k8s cluster (e.g. via `kubectl apply -f dist/`). However, it's possible for nested charts to cause resources to be listed twice. This PR resolves this by de-duplicating resources so that each one is only rendered once during a given "synth" call.

This PR makes the assumption that nesting charts within each other is implicitly a feature (I don't believe there are any other ways to arrive at charts containing the same resource twice?). It's possible we could instead add some kind of validation to prevent charts from being nested to resolve this issue instead, but this would become problematic if users are defining constructs that include charts.

Questions:
- Should there be some way to synthesize a specific chart within an app from the CLI?
- Should there be an option for synthesis (e.g. a CLI flag) to override this and allow duplicate objects?

### CODE REVIEW

File: src/app.ts [hunk 1]
```diff
@@ -90,16 +90,26 @@ export class App extends Construct {
...
+      const objects = new DependencyGraph(Node.of(chart)).topology()
+        .filter(x => (x instanceof ApiObject) && !found.has(x));
+
+      const chartName = namer.name(chart);
+      const manifestContents = objects.map(x => (x as ApiObject).toJson());
+      Yaml.save(path.join(this.outdir, chartName), manifestContents);
+
+      for (const obj of objects) {
+        found.add(obj);
+      }
```
Comment (Chriscbr) [inline src/app.ts:112]: Initially I was planning to go a step further and impose that if a chart is rendering no options, then it shouldn't bother creating a file/manifest for it (i.e. not just prune objects, but prune files as well) -- but there are currently unit tests that expect e.g. two empty charts to generate two empty files, so I guess the possibility of generating empty manifests is expected behavior.

File: test/app.test.ts [hunk 2]
```diff
@@ -163,6 +163,45 @@ test('app with chart dependencies via custom constructs', () => {
...
+  expect(fs.readdirSync(app.outdir)).toEqual([
+    '0000-chart1-chart2-c883b207.k8s.yaml',
+    '0001-chart1.k8s.yaml',
+  ]);
+  expect(fs.readFileSync(path.join(app.outdir, '0000-chart1-chart2-c883b207.k8s.yaml'), 'utf8')).toMatchSnapshot();
+  expect(fs.readFileSync(path.join(app.outdir, '0001-chart1.k8s.yaml'), 'utf8')).toMatchSnapshot();
+
+  // individual rendered charts may still share objects
+  expect(Testing.synth(chart)).toMatchObject([
+    { apiVersion: 'v1', kind: 'CustomConstruct', metadata: { name: 'chart1-chart2-child2-child2obj-c828dca6' } },
```
Comment (iliapolo) [inline test/app.test.ts:196]: Why would this resource be included in the parent chart? Even if its rendered individually, the resource itself isn't being added to this chart, only to the child chart. 

At the end of the day, only two resources are being created here, so I'd expect to only see 2 resources in the final result, here you have 3, 2 of which are duplicated.

File: test/app.test.ts [hunk 3]
```diff
@@ -163,6 +163,45 @@ test('app with chart dependencies via custom constructs', () => {
 
 });
 
+test('app with nested charts will deduplicate api objects', () => {
```
Comment (iliapolo) [inline test/app.test.ts:166]: Can you also a test case that explicitly simulates the scenario reported in the issue? This stuff is hard to reason about and I want to make sure we address the initial report.

File: src/app.ts (hunk 1 above)
Comment (iliapolo) [reply src/app.ts:112]: Generating empty is the expected behavior yes, `new Chart` is equivalent to manually create a manifest file.

File: src/app.ts [hunk 4]
```diff
@@ -143,6 +155,23 @@ function resolveDependencies(app: App) {
...
+      // create an explicit chart dependency from nested chart relationships
+      const parentChart = Chart.of(parent);
+      const childChart = Chart.of(child);
+
+      if (parentChart !== childChart && Node.of(parent).tryFindChild(Node.of(child).id)) {
+        Node.of(parentChart).addDependency(childChart);
+        hasDependantCharts = true;
+      }
+    }
+  }
```
Comment (iliapolo) [inline src/app.ts:173]: Simpler alternative: 

```suggestion
for (const parentChart of charts) {
  for (const childChart of Node.of(parentChart).children.filter(x => x instanceof Chart)) {

    // create an explicit chart dependency from nested chart relationships
    Node.of(parentChart).addDependency(childChart);
    hasDependantCharts = true;
  }
}
```

**Review by iliapolo — CHANGES_REQUESTED** [review]

File: test/app.test.ts (hunk 3 above)
Comment (Chriscbr) [reply test/app.test.ts:166]: Added.

**Comment by Chriscbr** [comment]
Per our discussion, I updated all synth methods so that the deduplication behavior is consistent across all of them.

**Review by iliapolo — APPROVED** [review]
