### PR TITLE
fix(chart): disable resource name hashes at chart level

### LINKED ISSUE #1037: Allow disabling name hashes on the chart level
Currently the hash of the construct path is always suffixed to the autogenerated resource name. We should add an option on the chart to opt-out of this. 

For example, the following code:

```ts
import { App, Chart } from 'cdk8s';
import * as kplus from 'cdk8s-plus-25';

const app = new App();
const chart = new MyChart(app, 'my-chart');

new kplus.Deployment(chart, 'Deployment', {
  containers: [{ image: 'nginx' }]
});

app.synth();
```

Will generate a `Deployment` resource with the following name: `my-chart-deployment-c8c354dd`. 

> See https://docs.aws.amazon.com/cdk/v2/guide/identifiers.html#identifiers_unique_ids for reasoning why we add the hash.

In some cases the hash is undesirable and currently users are forced to override the `Chart.generateObjectName` method to drop the hashes. Lets make this easier by adding a chart property that allows dropping the hashes.

> See https://github.com/cdk8s-team/cdk8s/issues/232

### PR DESCRIPTION
**Pull request by sumupitchayan**
Fixes #1037 

Added an `disableResourceNameHashes` property to `ChartProps` which is set to `false` by default. If set to true, then all resources inside of a chart will no longer have the hash value suffixed on their resource names.

Created a test called "disabling resource name hashes at chart level" in test/chart.test.ts to verify these changes are working.

This fix should also apply to [this issue](https://github.com/cdk8s-team/cdk8s/issues/232) requesting documentation about name generation.

### CODE REVIEW

File: src/chart.ts [hunk 1]
```diff
@@ -61,10 +69,16 @@ export class Chart extends Construct {
    */
   private readonly _labels?: { [name: string]: string };
 
+  /**
+   * Determines if resource names in the chart have the suffixed hash.
+   */
+  private _enableResourceNameHashes?: boolean;
```
Comment (vinayak-kukreja) [inline src/chart.ts]: Can you add `readonly` to this?

File: src/chart.ts [hunk 2]
```diff
@@ -61,10 +69,16 @@ export class Chart extends Construct {
...
+
   constructor(scope: Construct, id: string, props: ChartProps = { }) {
     super(scope, id);
     this.namespace = props.namespace;
     this._labels = props.labels ?? {};
+    this._enableResourceNameHashes = props.enableResourceNameHashes;
```
Comment (vinayak-kukreja) [inline src/chart.ts]: Hey, since this is default `true`, it can be added here,
```
    this._enableResourceNameHashes = props.enableResourceNameHashes ?? true;
```

File: test/chart.test.ts [hunk 3]
```diff
@@ -15,6 +15,23 @@ test('empty stack', () => {
   expect(Testing.synth(chart)).toMatchSnapshot();
 });
 
+test('disabling resource name hashes at chart level', () => {
```
Comment (vinayak-kukreja) [inline test/chart.test.ts:18]: Can you add a happy case scenario here too? Which would be that automatic hashes are working by default.

**Review by vinayak-kukreja — CHANGES_REQUESTED** [review]
Hey Sumu, great work. Let me know if my comments make sense. :)

**Comment by vinayak-kukreja** [comment]
Also, I see `DCO` check if failing for this PR. Let me know if you need any help with that.

File: src/chart.ts [hunk 4]
```diff
@@ -22,6 +22,14 @@ export interface ChartProps {
    */
   readonly labels?: { [name: string]: string };
 
+  /**
+   * The autogenerated resource name by default is suffixed with a stable hash
+   * of the construct path. Setting this property to false drops the hash suffix.
+   *
+   * @default true
+   */
+  readonly enableResourceNameHashes?: boolean;
```
Comment (iliapolo) [inline src/chart.ts]: Normally to activate a feature, we set a certain property to `true`, not `false`. The feature we want to activate here is actually to *disable* hashes...So I would suggest:

```suggestion
  readonly disableResourceNameHashes?: boolean;
```

And set the default to `false`. This would allow to set `disableResourceNameHashes: true`, which conveys the user intent more clearly I think.

File: test/chart.test.ts [hunk 5]
```diff
@@ -15,6 +15,38 @@ test('empty stack', () => {
...
+  // GIVEN
+  const app = Testing.app();
+  const chart = new Chart(app, 'test');
+
+  // WHEN
+  const ob1 = new ApiObject(chart, 'resource1', { kind: 'Resource1', apiVersion: 'v1' });
+  const ob2 = new ApiObject(chart, 'resource2', { kind: 'Resource3', apiVersion: 'v1' });
+
+  // THEN
+  expect(ob1.name).not.toEqual('test-resouce1');
```
Comment (iliapolo) [inline test/chart.test.ts]: Better to assert the positive instead of the negative, since the negative would make this test pass even if the name is completely different than what we expect. 

```suggestion
  expect(ob1.name).toEqual('test-resouce1');
```

**Review by iliapolo — CHANGES_REQUESTED** [review]

**Review by iliapolo — APPROVED** [review]
👍

**Review by vinayak-kukreja — APPROVED** [review]

**Comment by iliapolo** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.x|[](https://github.com/cdk8s-team/cdk8s-core/pull/1102)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
