### PR TITLE
fix: app `outdir` property cannot be different from CLI or cdk8s.yaml file

### LINKED ISSUE #210: CLI throws faulty error when outdir is passed to AppProps
### Description of the bug:

Configuration of the output directory `outdir` for manifests file in the App construct results in an error message with the default output directory (`dist`)

 I am using the following:
* Python 3.7.10
* cdk8s-cli 1.0.107
* cdk8s==1.5.8
* cdk8s-plus-22==1.0.0b109

### Reproduction Steps:

```
from constructs import Construct
from cdk8s import App, Chart
app = App(
    outdir="manifests"
)
```

### Error Log:

After running `cdk8s synth`:
```
ERROR: synthesis failed, app expected to create "dist"
```

### Environment:

  - **Framework Version**: 1.5.8
  - **OS**: AL2

```
attrs==21.4.0
cattrs==1.10.0
cdk8s==1.5.8
cdk8s-plus-22==1.0.0b109
constructs==3.3.209
jsii==1.52.1
publication==0.0.3
python-dateutil==2.8.2
six==1.16.0
typing_extensions==4.0.1
```

### Other:

---

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by vinayak-kukreja**
Currently setting the `outdir` property for CDK8s app throws an error,
```
ERROR: synthesis failed, app expected to create "dist"
```

This is due to the CLI not able to recognize this change in the `outdir` in the application property. 
The value specified in the `outdir` needs to be similar to what is mentioned either in CLI's `--output` argument or the `output` property in the cdk8s.yaml file. 

Signed-off-by: Vinayak Kukreja <vinakuk@amazon.com>

Resolves https://github.com/cdk8s-team/cdk8s-cli/issues/210

### CODE REVIEW

File: src/app.ts [hunk 1]
```diff
@@ -23,6 +23,13 @@ export interface AppProps {
   /**
    * The directory to output Kubernetes manifests.
    *
+   * By default, the value you pass to the CDK8s CLI's `--output` flag
+   * or in the `output` property of cdk8s.yaml file will be used,
+   * and if you change it to a different directory the CLI will fail
+   * to pick up the new output directory.
+   *
+   * This property is intended for internal and testing use.
+   *
```
Comment (iliapolo) [inline src/app.ts]: Where not focusing on the default behavior, but rather on the conflicts that may arise. 

```suggestion
   * If you synthesize your application using `cdk8s synth`, you must also pass this value to the CLI using the `-- 
   * output` option or the `output` property in the `cdk8s.yaml` configuration file. 
   * Otherwise, the CLI will not know about the output directory, and synthesis will fail. 
   * 
   * This property is intended for internal and testing use.
   *
```

**Review by iliapolo — CHANGES_REQUESTED** [review]

File: src/app.ts (hunk 1 above)
Comment (vinayak-kukreja) [reply src/app.ts]: I see, ok, will make this update.

**Review by iliapolo — APPROVED** [review]
